<?php

namespace ContainerGZo2w0t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_115ctMjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.115ctMj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.115ctMj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'link' => ['privates', '.errored..service_locator.115ctMj.App\\Entity\\Link', NULL, 'Cannot autowire service ".service_locator.115ctMj": it references class "App\\Entity\\Link" but no such service exists.'],
        ], [
            'link' => 'App\\Entity\\Link',
        ]);
    }
}
