<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZo2w0t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZo2w0t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGZo2w0t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGZo2w0t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGZo2w0t\App_KernelDevDebugContainer([
    'container.build_hash' => 'GZo2w0t',
    'container.build_id' => 'af48a9d6',
    'container.build_time' => 1661332882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZo2w0t');
